import Head from 'next/head'
import { useRouter } from 'next/router'
import React from 'react'
import POVDisplay from '../components/POVDisplay'

export default function DisplayPage() {
  const router = useRouter()
  // @ts-ignore
  const delay = router.query.delay as number
  const word = router.query.word as string || 'N'
  return (
    <div className='bg-black min-h-full flex flex-col items-center justify-center'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
      </Head>

      <span className='text-center text-gray-800'>Delay: {delay} || word: {word}</span>
      <div className='bg-black min-h-full flex flex-col items-center justify-center'>
        <POVDisplay word={word} delay={1} />
      </div>
    </div>
  )
}
